headless: false

env:
  num_envs: 4096
  env_spacing: 6
  max_episode_length: 500
  min_episode_length: 50

sim:
  dt: 0.016
  substeps: 1
  gravity: [0, 0, -9.81]
  replicate_physics: false
  use_flatcache: true
  use_gpu_pipeline: true
  device: "cuda"

  solver_type: 1
  use_gpu: True # set to False to run on CPU
  bounce_threshold_velocity: 0.2
  friction_offset_threshold: 0.04
  friction_correlation_distance: 0.025
  enable_stabilization: True

  # GPU buffers
  gpu_max_rigid_contact_count: 524288
  gpu_max_rigid_patch_count: 81920
  gpu_found_lost_pairs_capacity: 4194304
  gpu_found_lost_aggregate_pairs_capacity: 33554432
  gpu_total_aggregate_pairs_capacity: 4194304
  gpu_max_soft_body_contacts: 1048576
  gpu_max_particle_contacts: 1048576
  gpu_heap_capacity: 67108864
  gpu_temp_buffer_capacity: 16777216
  gpu_max_num_partitions: 8

viewer:
  eye: [7.5, 7.5, 7.5]
  lookat: [0., 0., 0.]

wandb:
  group: ${oc.select:..task.name}
  run_name: ${oc.select:..task.name,test}
  job_type: train
  entity: marl-drones
  project: gpu-onpolicy
  mode: online # set to 'disabled' when debugging locally
  run_id: 
  run_path:
  monitor_gym: True
  log_code: True
  tags: 

defaults:
  - task: Hover
  - algo: mappo
  - _self_
