headless: false

sim: ${task.sim}
env: ${task.env}

total_frames: -1

viewer:
  eye: [7.5, 7.5, 7.5]
  lookat: [0., 0., 0.]

wandb:
  group: ${oc.select:..task.name}
  run_name: ${oc.select:..task.name,test}
  job_type: train
  entity: marl-drones
  project: gpu-onpolicy
  mode: online # set to 'disabled' when debugging locally
  run_id: 
  run_path:
  monitor_gym: True
  log_code: True
  tags: 

defaults:
  - task: Hover
  - algo: mappo
  - _self_
