# model_dir: /home/chenjy/OmniDrones/scripts/outputs/random0to3_final/v2_0_catch0_2_height0_6_size0_9.pt
# model_dir: /home/chenjy/OmniDrones/scripts/outputs/final_results/DR_wovalidation/seed0/v1_6_catch0_2_height1_2_size0_9.pt
# model_dir: null
# model_dir: /home/chenjy/OmniDrones/scripts/outputs/final_results/cl_final/v1_2_catch0_2.pt
model_dir: /home/chenjy/OmniDrones/scripts/outputs/final_results/cl_new_reward/v1_2_catch0_15.pt

# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

total_frames: 100_000_000_000
max_iters: -1
eval_interval: 200
save_interval: 200
seed: 0

viewer:
  resolution: [960, 720]
  # up
  eye: [0.001, 0.0, 6.]
  lookat: [0., 0., 2.]
  # # front
  # eye: [3., 3., 3.5]
  # lookat: [0., 0., 0.7]

wandb:
  group: ${oc.select:..task.name}
  run_name: cl_new_reward_v1_2_catch0_12
  # run_name: targetclip_01
  # run_name: debug
  job_type: train
  entity: chenjy
  project: PredatorPrey
  mode: online
  # mode: disabled # set to 'disabled' when debugging locally
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  - task: HideAndSeek_circle_static_UED_large_cylinder_cl_v2
  # - task: HideAndSeek_circle_eval_large
  - algo: mappo
  - _self_
