# exp
num_agents: 3
num_obstacles: 5
obstacle_size: 0.05
v_drone: 1.0
v_low: 1.3
v_high: 5.0
v_obstacle_min: 1.0
v_obstacle_max: 5.0
size_min: 0.5
size_max: 1.0
obstacle_control_fre: 20
fixed_config: False # if True, only eval max_config
# model_dir: /root/OmniDrones/scripts/outputs/5obstacle_size1_speed5_obstaclespeed5_decay0_cl_various/10-17_10-51/wandb/run-20231017_105104-ykhedgrr/files/checkpoint_15500_5079367680.pt
model_dir: null
use_collision: 1
use_speed_penalty: 1
catch_radius: 0.15
collision_radius: 0.01
use_dynamic: False

# cl
prob_curriculum: 0.9
prob_decay: 2

# hydra.job.chdir: false

headless: false

sim: ${task.sim}
env: ${task.env}

# total_frames: 250_000_000
# max_iters: -1
# eval_interval: -1
# save_interval: -1
# seed: 0
total_frames: 100_000_000_000
max_iters: 5000
eval_interval: 100
save_interval: 100
seed: 1

viewer:
  resolution: [960, 720]
  # eye: [8, 0., 6.]
  # lookat: [0., 0., 1.]
  eye: [2, 2, 2]
  lookat: [0., 0., 0.]

wandb:
  group: ${oc.select:..task.name}
  run_name: ${oc.select:..task.name,test}-${oc.select:..algo.name,none}
  job_type: train
  entity: nics_marl
  project: omnidrones
  mode: online # set to 'disabled' when debugging locally
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  - task: PredatorPrey_cl
  - algo: mappo
  - _self_
