# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

# model_dir: /home/jiayu/OmniDrones/scripts/outputs/multigoto_smooth02_Tm04.pt
# model_dir: /home/jiayu/OmniDrones/scripts/outputs/multigo_wosmooth_point3/06-19_22-33/wandb/run-20240619_223352-rtx5hsw1/files/checkpoint_final.pt
model_dir: null

total_frames: 3000_000_000 #1000_000_000
max_iters: -1
eval_interval: -1
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  # up
  # eye: [0.005, 0., 6.]
  # lookat: [0., 0., 1.]
  # front
  eye: [1., 0., 4.]
  lookat: [0., 0., 1.]

wandb:
  group: ${oc.select:..task.name}
  # run_name: multigo_wosmooth_point2_large
  run_name: exchange_wosmooth
  # run_name: debug
  job_type: train
  entity: chenjy
  project: sim2real
  # mode: disabled
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  # - task: Star
  # - task: Track
  - task: Exchange
  # - task: MultiGoto
  - algo: mappo
  - _self_
