# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

model_dir: /home/jiayu/OmniDrones/scripts/outputs/ours_deploy.pt
# model_dir: /home/jiayu/OmniDrones/scripts/outputs/ours_best.pt
# model_dir: null

total_frames: 6000_000_000 #1000_000_000
max_iters: -1
eval_interval: -1
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  # up
  eye: [-0.005, 0.0, 5.]
  lookat: [0., 0., 1.]
  # eye: [-2.5, 0.0, 2.]
  # lookat: [0., 0.0, 0.1]

wandb:
  group: ${oc.select:..task.name}
  # run_name: random4to5_smooth1_20125_lr00001_load_ctbr0_2_load
  run_name: best_random4to5_maxsmooth15_init15_load_load
  entity: chenjy
  project: RAL
  # mode: disabled
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags:

defaults:
  # - task: HideAndSeek_square_partial
  - task: HideAndSeek_circle_partial_TP
  # - task: HideAndSeek_circle_partial_TP_particle
  - algo: mappo
  - _self_