# model_dir: /home/chenjy/OmniDrones/scripts/outputs/random0to3_final/v2_0_catch0_2_height0_6_size0_9.pt
# model_dir: /home/chenjy/OmniDrones/scripts/outputs/v1_6_cl_emptybuffer_from_heightbound0_3_threshold_1toinf/03-30_17-53/wandb/run-20240330_175303-f3mpf9ez/files/checkpoint_78774272.pt
model_dir: /home/chenjy/OmniDrones/scripts/outputs/cl_final/v1_2_catch0_2_height1_2_size0_9.pt
# model_dir: null

# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

total_frames: 100_000_000_000
max_iters: -1
eval_interval: 200
save_interval: 200
seed: 0

viewer:
  resolution: [960, 720]
  # # up
  # eye: [0.001, 0.0, 6.]
  # lookat: [0., 0., 2.]
  # # debug
  # eye: [0., -4., 4.]
  # lookat: [0., 0., 1.]
  # front
  eye: [0., 4., 4.]
  lookat: [0., 0., 1.]

wandb:
  group: ${oc.select:..task.name}
  # run_name: debug
  run_name: v1_6_cl_emptybuffer_from_heightbound0_3_threshold_1toinf
  job_type: train
  entity: chenjy
  project: PredatorPrey
  mode: online
  # mode: disabled # set to 'disabled' when debugging locally
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  # - task: HideAndSeek_circle_static_UED_addeasy
  # - task: HideAndSeek_circle_static_UED_cl
  # - task: HideAndSeek_circle_static_UED_cl_v2
  # - task: HideAndSeek_circle_static_UED
  # - task: HideAndSeek_circle_static_UED_large_cylinder
  # - task: HideAndSeek_circle_static_UED_large_cylinder_cl
  - task: HideAndSeek_circle_static_UED_large_cylinder_cl_v2
  # - task: HideAndSeek_circle_eval
  # - task: HideAndSeek_circle_eval_large
  - algo: mappo
  - _self_
