# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

total_frames: 300_000_000 #1000_000_000
max_iters: -1
eval_interval: -1
save_interval: -1
seed: 0

viewer:
  resolution: [960, 720]
  eye: [8, 0., 6.]
  lookat: [0., 0., 1.]

wandb:
  group: ${oc.select:..task.name}
  run_name: Hover_crazyflie_origin_withrandom
  job_type: train
  entity: chenjy
  project: Hover
  mode: disabled # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  - task: Hover
  - algo: mappo
  - _self_
