# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

# model_dir: /home/jiayu/OmniDrones/scripts/outputs/multigo_smooth05_point2_large/06-20_14-57/wandb/run-20240620_145742-jwgk4kwo/files/checkpoint_1192886272.pt
# model_dir: /home/jiayu/OmniDrones/scripts/outputs/goto_static_wosmooth/06-22_14-23/wandb/run-20240622_142350-o2o04qkj/files/checkpoint_1271529472.pt
# model_dir: /home/jiayu/OmniDrones/scripts/outputs/goto_static_wosmooth/06-22_16-42/wandb/run-20240622_164253-tg1wboso/files/checkpoint_final.pt
model_dir: null

total_frames: 3000_000_000 #1000_000_000
max_iters: -1
eval_interval: -1
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  # front
  eye: [0.005, 0., 4.]
  lookat: [0., 0., 1.]
  # # follow drone
  # eye: [0., 2.0, 2.5]
  # lookat: [0., 0., 1.0]

wandb:
  group: ${oc.select:..task.name}
  # run_name: debug
  run_name: goto_static_wosmooth
  job_type: train
  entity: chenjy
  project: sim2real
  # mode: disabled
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  - task: Goto_static
  # - task: Track
  # - task: Exchange
  # - task: MultiGoto
  - algo: mappo
  - _self_
