# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

# model_dir: /home/jiayu/OmniDrones/scripts/outputs/Track_star_random.pt
model_dir: null

total_frames: 3000_000_000 #1000_000_000
max_iters: -1
eval_interval: 100
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  eye: [1.0, 0., 3.]
  lookat: [0., 0., 1.]

wandb:
  group: ${oc.select:..task.name}
  run_name: Track_smoothscale0_5_woup_spin_reward
  # run_name: debug
  job_type: train
  entity: chenjy
  project: Track
  # mode: disabled
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  - task: Track
  # - task: Line
  # - task: Hover
  - algo: mappo
  - _self_
