model_dir: /home/jiayu/OmniDrones/scripts/outputs/random3_large_catch0_2_v_1_3_fixed1.pt
# model_dir: /home/chenjy/OmniDrones/scripts/outputs/cl_catch0_15_collision001_validation.pt
# model_dir: /home/jiayu/OmniDrones/scripts/outputs/fixed3_final/v1_3_catch0_2_height0_6_size0_6.pt
# model_dir: null

# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

total_frames: 100_000_000_000
max_iters: -1
eval_interval: 100
save_interval: 200
seed: 0

viewer:
  resolution: [960, 720]
  # # up
  # eye: [0.001, 0.0, 6.]
  # lookat: [0., 0., 2.]
  # # debug
  # eye: [0., -4., 4.]
  # lookat: [0., 0., 1.]
  # front
  eye: [0., 4., 4.]
  lookat: [0., 0., 1.]

wandb:
  group: ${oc.select:..task.name}
  run_name: fixed3_v1_3_catch0_2_size0_9
  # run_name: large_debug
  job_type: train
  entity: chenjy
  project: PredatorPrey
  mode: online
  # mode: disabled # set to 'disabled' when debugging locally
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  # - task: HideAndSeek_circle_static_UED_addeasy
  # - task: HideAndSeek_circle_static_UED_cl
  # - task: HideAndSeek_circle_static_UED_cl_v2
  # - task: HideAndSeek_circle_static_UED
  # - task: HideAndSeek_circle_static_UED_large_cylinder
  # - task: HideAndSeek_circle_static_UED_large_cylinder_cl
  - task: HideAndSeek_circle_static_UED_large_cylinder_cl_v2
  # - task: HideAndSeek_circle_eval
  # - task: HideAndSeek_circle_eval_large
  - algo: mappo
  - _self_
