# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

# model_dir: /home/jiayu/OmniDrones/scripts/outputs/GAN0to5_catch0_3_v1_3_TP_arena0_9_GAN1_unif0/08-07_22-11/wandb/run-20240807_221127-8yx6yiss/files/checkpoint_1822031872.pt
# model_dir: /home/jiayu/OmniDrones/scripts/outputs/random0to5_catch0_3_v1_3_TP_arena0_9/08-07_16-28/wandb/run-20240807_162823-ielzqj9c/files/checkpoint_563740672.pt
model_dir: null

total_frames: 3000_000_000 #1000_000_000
max_iters: -1
eval_interval: -1
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  # up
  eye: [-0.005, 0.0, 5.]
  lookat: [0., 0., 1.]
  # eye: [-2.5, 0.0, 2.]
  # lookat: [0., 0.0, 0.1]

wandb:
  group: ${oc.select:..task.name}
  # run_name: debug
  run_name: GAN0to5_GAN1_min0_5_max0_9
  # run_name: random0to5_fixedinitxy
  job_type: train
  entity: chenjy
  project: RAL
  # mode: disabled
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags:

defaults:
  # - task: HideAndSeek_square_partial
  # - task: HideAndSeek_circle_partial_woTP
  # - task: HideAndSeek_circle_partial_TP
  - task: HideAndSeek_circle_partial_TP_GAN
  - algo: mappo
  - _self_
