# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

# model_dir: /home/chenjy/OmniDrones/scripts/outputs/fully_TP_catch0_5_history5_future5_windowstep10_slowtarget1/07-14_11-34/wandb/run-20240714_113426-nwonl28l/files/checkpoint_550764544.pt
model_dir: null

total_frames: 3000_000_000 #1000_000_000
max_iters: -1
eval_interval: -1
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  # front
  eye: [0., -0.005, 4.]
  lookat: [0., 0., 1.]
  # eye: [0., -5.0, 10.]
  # lookat: [0., 4.0, 1.]

wandb:
  group: ${oc.select:..task.name}
  run_name: catch0_5_target1_history10_future5_windowstep10_TP
  # run_name: debug
  job_type: train
  entity: chenjy
  project: pursuit-evasion
  # mode: disabled
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  - task: HideAndSeek_square
  # - task: Track
  - algo: mappo
  - _self_
