# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

# model_dir: /home/jiayu/OmniDrones/scripts/outputs/Track_size05to08_smooth0_reward_up_spin/05-28_10-28/wandb/run-20240528_102811-crgu03wi/files/checkpoint_603062272.pt
# model_dir: /home/jiayu/OmniDrones/scripts/outputs/Go_return_reach_and_return_load/06-13_16-05/wandb/run-20240613_160544-yvlac912/files/checkpoint_943980544.pt
# model_dir: /home/jiayu/OmniDrones/scripts/outputs/Go_static/06-16_17-30/wandb/run-20240616_173013-hrtosiih/files/checkpoint_341049344.pt
model_dir: null

total_frames: 3000_000_000 #1000_000_000
max_iters: -1
eval_interval: -1
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  # up
  # eye: [0.005, 0., 6.]
  # lookat: [0., 0., 1.]
  # front
  eye: [1.0, 0., 4.]
  lookat: [0., 0., 1.]

wandb:
  group: ${oc.select:..task.name}
  run_name: Goto_static
  # run_name: Goto_static_undergroundcylinder
  # run_name: debug
  job_type: train
  entity: chenjy
  project: sim2real
  # mode: disabled
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  # - task: Star
  # - task: Track
  - task: Goto_static
  # - task: MultiGoto
  - algo: mappo
  - _self_
