# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

# model_dir: /home/jiayu/OmniDrones/scripts/outputs/drone3_arena2/07-07_18-06/wandb/run-20240707_180621-e6bnfxns/files/checkpoint_603193344.pt
model_dir: null

total_frames: 3000_000_000 #1000_000_000
max_iters: -1
eval_interval: -1
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  # front
  eye: [0., -0.005, 4.]
  lookat: [0., 0., 1.]
  # # follow drone
  # eye: [0., 2.0, 2.5]
  # lookat: [0., 0., 1.0]

wandb:
  group: ${oc.select:..task.name}
  run_name: fixedtarget_arena2
  job_type: train
  entity: chenjy
  project: pursuit-evasion
  # mode: disabled
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  - task: HideAndSeek_square
  # - task: Track
  - algo: mappo
  - _self_
