# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

# model_dir: /home/jiayu/OmniDrones/scripts/outputs/Track_Tm0349_smooth05.pt
# model_dir: /home/jiayu/OmniDrones/scripts/outputs/Track_Tm0349_wosmooth.pt
# model_dir: /home/jiayu/OmniDrones/scripts/outputs/Track_Tm04_smooth05.pt
# model_dir: /home/jiayu/OmniDrones/scripts/outputs/Track_Tm04_wosmooth.pt
# model_dir: /home/jiayu/OmniDrones/scripts/outputs/Track_Tm043_smooth05.pt
# model_dir: /home/jiayu/OmniDrones/scripts/outputs/Track_Tm04_wosmooth_new.pt
model_dir: null

total_frames: 3000_000_000 #1000_000_000
max_iters: -1
eval_interval: -1
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  # up
  # eye: [0.005, 0., 6.]
  # lookat: [0., 0., 1.]
  # front
  eye: [1.0, 0., 4.]
  lookat: [0., 0., 1.]

wandb:
  group: ${oc.select:..task.name}
  # run_name: Goto_static_smooth1
  # run_name: debug
  run_name: Track_smooth_latency3
  job_type: train
  entity: chenjy
  project: sim2real
  # mode: disabled
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  # - task: Star
  - task: Track
  # - task: Goto_static
  # - task: MultiGoto
  - algo: mappo
  - _self_
