# model_dir: /home/chenjy/OmniDrones/scripts/outputs/virtual_cylinder_0to5_catch0_15.pt
model_dir: /home/chenjy/OmniDrones/scripts/outputs/cylinder0to5_catch0_2.pt
# model_dir: null

# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

total_frames: 100_000_000_000
max_iters: -1
eval_interval: 50
save_interval: 200
seed: 0

viewer:
  resolution: [960, 720]
  # up
  eye: [0.001, 0.0, 6.]
  lookat: [0., 0., 2.]
  # # debug
  # eye: [0., -4., 4.]
  # lookat: [0., 0., 1.]
  # # front
  # eye: [8., 0., 8.]
  # lookat: [0., 0., 1.]

wandb:
  group: ${oc.select:..task.name}
  # run_name: virtual_cylinder_0to5_random_catch0_15_loadcatch0_2
  run_name: cylinder0to5_catch0_15_collision001_cl_generate_env_loadcatch0_2
  # run_name: debug
  job_type: train
  entity: chenjy
  project: PredatorPrey
  mode: online
  # mode: disabled # set to 'disabled' when debugging locally
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  # - task: HideAndSeek
  - task: HideAndSeek_circle_static_UED_cl
  # - task: HideAndSeek_circle_static_UED
  # - task: HideAndSeek_circle_static_UED_cl_v2
  # - task: HideAndSeek_circle_eval
  - algo: mappo
  - _self_
