# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

# model_dir: /home/jiayu/OmniDrones/scripts/outputs/Track_large_smooth0_fixedz/05-26_22-07/wandb/run-20240526_220720-b3lx8h3c/files/checkpoint_final.pt
model_dir: null

total_frames: 3000_000_000 #1000_000_000
max_iters: -1
eval_interval: 100
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  eye: [0.005, 0., 10.]
  lookat: [0., 0., 1.]

wandb:
  group: ${oc.select:..task.name}
  # run_name: debug
  run_name: Track_large_smooth0_fixedz
  job_type: train
  entity: chenjy
  project: Track
  # mode: disabled
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  # - task: Infeasible
  - task: Track
  # - task: Line
  # - task: Hover
  - algo: mappo
  - _self_
