# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

# model_dir: /home/jiayu/OmniDrones/scripts/outputs/Line_a1to3_worewardup/05-20_21-10/wandb/run-20240520_211011-p5caagxx/files/checkpoint_final.pt
model_dir: null

total_frames: 3000_000_000 #1000_000_000
max_iters: -1
eval_interval: -1
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  eye: [1.0, 0., 8.]
  lookat: [2., 0., 1.]

wandb:
  group: ${oc.select:..task.name}
  run_name: Track_star_cf12
  # run_name: debug
  job_type: train
  entity: chenjy
  project: Track
  # mode: disabled
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  # - task: Line
  - task: Track
  - algo: mappo
  - _self_
