# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

# model_dir: /home/chenjiayu/OmniDrones/scripts/outputs/Hover_crazyflie_origin_worandom_wolatency_little/12-07_16-38/wandb/run-20231207_163825-uvxd1nxx/files/checkpoint_final.pt
model_dir: null

total_frames: 3000_000_000 #1000_000_000
max_iters: -1
eval_interval: 200
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  eye: [4., 0., 4.]
  lookat: [0., 0., 1.]

wandb:
  group: ${oc.select:..task.name}
  run_name: Track_star_cf7opt_clip60_50HZ_Pcontroller
  # run_name: debug
  job_type: train
  entity: chenjy
  project: Track
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  # - task: Hover
  - task: Track
  - algo: mappo
  - _self_
