# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

# model_dir: /home/jiayu/OmniDrones/scripts/outputs/catch0_5_TP_window1/07-19_12-00/wandb/run-20240719_120034-qehz35x7/files/checkpoint_629407744.pt
# model_dir: /home/jiayu/OmniDrones/scripts/outputs/1corner.pt
model_dir: null

total_frames: 3000_000_000 #1000_000_000
max_iters: -1
eval_interval: -1
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  # up
  eye: [-0.005, 0.0, 5.]
  lookat: [0., 0., 1.]
  # eye: [-0.7, 0.0, 2.]
  # lookat: [0., 0.0, 1.]

wandb:
  group: ${oc.select:..task.name}
  run_name: 2cylinders_woTP_wosmooth_newreward
  # run_name: narrow
  job_type: train
  entity: chenjy
  project: pursuit-evasion
  # mode: disabled
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  - task: HideAndSeek_square_partial
  # - task: Track
  - algo: mappo
  - _self_
