# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

total_frames: 200_000_000 #1000_000_000
max_iters: -1
eval_interval: 500
save_interval: 500
seed: 0

viewer:
  resolution: [960, 720]
  eye: [8, 0., 6.]
  lookat: [0., 0., 1.]

wandb:
  group: ${oc.select:..task.name}
  run_name: ${oc.select:..task.name,test}-${oc.select:..algo.name,none}-${oc.select:..task.stage,none}
  job_type: train
  entity: marl-drones
  project: omnidrones
  mode: online # set to 'disabled' when debugging locally
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  - task: FormationBallForward
  - algo: mappo
  - _self_
