# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

# model_dir: /home/jiayu/OmniDrones/scripts/outputs/catch0_5_TP_window1/07-19_12-00/wandb/run-20240719_120034-qehz35x7/files/checkpoint_629407744.pt
# model_dir: /home/jiayu/OmniDrones/scripts/outputs/empty_catch0_3_v1_3/07-28_22-59/wandb/run-20240728_225903-ud3zthal/files/checkpoint_1822031872.pt
model_dir: null

total_frames: 3000_000_000 #1000_000_000
max_iters: -1
eval_interval: -1
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  # # up
  eye: [-0.005, 0.0, 5.]
  lookat: [0., 0., 1.]
  # eye: [-2.0, 0.0, 5.]
  # lookat: [0., 0.0, 1.0]

wandb:
  group: ${oc.select:..task.name}
  run_name: empty_catch0_3_v1_3
  # run_name: debug
  job_type: train
  entity: chenjy
  project: RAL
  # mode: disabled
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  # - task: HideAndSeek_square_partial
  - task: HideAndSeek_circle_partial
  # - task: Track
  - algo: mappo
  - _self_
