name: sac

buffer_size: 409600
train_every: 32
batch_size: 4096
gamma: 0.95
tau: 0.005
max_grad_norm: 5

share_actor: true

gradient_steps: 1024

actor:
  hidden_units: [256, 128]
  lr: 0.0005
  layer_norm: true

critic:
  hidden_units: [256, 128]
  lr: 0.0005
  layer_norm: true

critic_loss: smooth_l1
alpha_lr: 0.0001

actor_delay: 2
target_update_interval: 4
