name: sac

buffer_size: 819200
train_every: 20
batch_size: 2560
gamma: 0.95
tau: 0.005
reward_weights: null
max_grad_norm: 5

share_actor: true

gradient_steps: 1024

actor:
  hidden_units: [128, 128]
  lr: 0.0005
  layer_norm: true

critic:
  hidden_units: [128, 128]
  lr: 0.0005
  layer_norm: true

critic_loss: smooth_l1
alpha_lr: 0.0001

actor_delay: 2
target_update_interval: 4
