name: td3

buffer_size: 409600
train_every: 32
batch_size: 4096
gamma: 0.95
tau: 0.005
max_grad_norm: 5

gradient_steps: 640
target_noise: 0.05
policy_noise: 0.1
noise_clip: 0.2

actor:
  hidden_units: [256, 128]
  lr: 0.0005
  layern_norm: true

critic:
  hidden_units: [256, 128]
  lr: 0.0005
  layer_norm: true

critic_loss: mse_loss

actor_delay: 2
target_update_interval: 4