name: tdmpc

actor:
  hidden_units: [128]
  lr: 3e-4
model:
  hidden_dim: 128
  encoder:
    hidden_units: [256, 128]
  dynamics:
    hidden_units: [128]
  lr: 3e-4
max_grad_norm: 10


# cem planning
num_samples: 512
min_std: 0.05
mixture_coef: 0.05
gamma: 0.99
cem_momentum: 0.1
cem_iterations: 8
cem_num_elites: 64
cem_temperature: 0.5

# model learning
horizon: 5
reward_coef: 0.5
value_coef: 0.1
consistency_coef: 2
target_update_interval: 2
tau: 0.01
rho: 0.5

buffer_size: 1024
batch_size: 256
batch_length: 5
train_every: 64
gradient_steps: 512

horizon_schedule: "linear(1, ${.horizon}, 25000)"
std_schedule: "linear(0.5, ${.min_std}, 25000)"